export const GET_TUTORIALS_REQUEST = "GET_TUTORIAL_REQUEST";
export const GET_TUTORIALS_SUCCESS = "GET_TUTORIALS_SUCCESS";
export const GET_TUTORIALS_FAILURE = "GET_TUTORIALS_FAILURE";

export const ADD_TUTORIAL_REQUEST = "ADD_TUTORIAL_REQUEST";
export const ADD_TUTORIAL_SUCCESS = "ADD_TUTORIAL_SUCCESS";
export const ADD_TUTORIAL_FAILURE = "ADD_TUTORIAL_FAILURE";
export const ADD_TUTORIAL_RESET = "ADD_TUTORIAL_RESET";

export const UPDATE_TUTORIAL_REQUEST = "UPDATE_TUTORIAL_REQUEST";
export const UPDATE_TUTORIAL_SUCCESS = "UPDATE_TUTORIAL_SUCCESS";
export const UPDATE_TUTORIAL_FAILURE = "UPDATE_TUTORIAL_FAILURE";
export const UPDATE_TUTORIAL_RESET = "UPDATE_TUTORIAL_RESET";

export const DELETE_TUTORIAL_REQUEST = "DELETE_TUTORIAL_REQUEST";
export const DELETE_TUTORIAL_SUCCESS = "DELETE_TUTORIAL_SUCCESS";
export const DELETE_TUTORIAL_FAILURE = "DELETE_TUTORIAL_FAILURE";
export const DELETE_TUTORIAL_RESET = "DELETE_TUTORIAL_RESET";

export const DELETE_ALL_TUTORIALS_REQUEST = "DELETE_ALL_TUTORIALS_REQUEST";
export const DELETE_ALL_TUTORIALS_SUCCESS = "DELETE_ALL_TUTORIALS_SUCCESS";
export const DELETE_ALL_TUTORIALS_FAILURE = "DELETE_ALL_TUTORIALS_FAILURE";
export const DELETE_ALL_TUTORIALS_RESET = "DELETE_ALL_TUTORIALS_RESET";
